name: posapp
description: A simple POS app for small restaurants

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  animations: ^2.0.0
  provider: ^5.0.0
  localstorage:
    git:
      url: git://github.com/tcd93/flutter_localstorage
      ref: master
  image_picker: ^0.7.2
  image_picker_for_web: ^2.0.0
  blue_thermal_printer:
    git:
      url: git://github.com/tcd93/blue_thermal_printer
      ref: master
  google_fonts: ^2.0.0
  date_range_picker:
    git:
      url: git://github.com/tcd93/date_range_picker
      ref: master
  super_tooltip:
    git:
      url: git://github.com/tcd93/super_tooltip
      ref: master
  fl_chart: ^0.36.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - google_fonts/

flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/splash_icon_ios.png"
  image_path_android: "assets/app_icon/splash_icon_adaptive.png"
  adaptive_icon_background: '#FFFFFF'
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app_icon/splash_icon_ios.png"
    background_color: "#FFFFFF"
